### ISSUE TITLE
Python requirement for installation?

### ISSUE THREAD

**Issue by kalihos** [virtkick/http-master#120]
Hi.

I was looking for a reverse proxy to be able to handle N Node processes (one for each individual client), through port 80 and using subdomains. I tried to install globally using npm install -g http-master, but I got an error requesting Python installed in my system. Is this normal?

C:\Users\ecame\AppData\Roaming\npm\node_modules\http-master\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)

I'm installing on Windows 10 as my development environment, but I will install later on Windows Server 2008 in my production env.

Thanks a lot!
Enrique.

**Comment by Nowaker** [comment]
[node-gyp](https://github.com/nodejs/node-gyp) is used by node.js itself to build native dependencies. It's unfortunate they're using Python for that but that's how it is. There's nothing we can do.

Even if you make node-gyp work on Windows, you'll hit other problems. http-master doesn't officially support Windows. We'll accept pull requests, though!

Have a good one,
-Damian

**Comment by Rush** [comment]
@kalihos I think once you install python everything should work on Windows. Let us know if it is the case.

**Comment by kalihos** [comment]
Hi all.

I tried to install Python, and I got another error due to the version installed (too new for the package, as I saw in the message). I installed then an older version, but suitable for this case, and I got another different error:

C:\Users\ecame\AppData\Roaming\npm\node_modules\http-master\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
C:\Users\ecame\AppData\Roaming\npm\node_modules\http-master\node_modules\bufferutil\build\bufferutil.vcxproj(20,3): err
or MSB4019: No se encuentra el proyecto importado "C:\Microsoft.Cpp.Default.props". Asegúrese de que la ruta de acceso
de la declaración <Import> es correcta y de que el archivo se encuentra en el disco.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)

So I decided to move to Nginx, because I have no change to work with Linux for the moment. Thank you very much for your replies.

Have a good day.
