### ISSUE TITLE
POST transformed to GET request

### ISSUE THREAD

**Issue by nickdbush** [virtkick/http-master#121]
I have used http-master for proxying requests for quite a while now, and this is the first problem that I have run into with the module. It simply redirects traffic on port 80 (HTTP) to port 443 (HTTPS). However, in the process, it (for some reason unknown to me) it transforms POST requests to GET requests instead.

This is in the log for the redirection route: ```POST /api/login HTTP/1.1" 302```
This is the route that forwards the HTTPS traffic to the correct port: ```GET /api/login HTTP/1.1" 404```

This is the guts of my server file:
```
ports: {
  80: {
    router: {
      'example.com': "redirect -> https://www.example.com/[path]", //This works
      ...
      'foo.example.com': ["log -> http.log", "redirect -> https://foo.example.com/[path]"] //This does not work
    }
  },
  443: {
    router: {
      'www.example.com': 1024,
      ...
      'foo.example.com': 1029
    }
}
```

How do I stop this from happening? It works fine for all my other routes!

**Comment by Rush** [comment]
Hmm, it seems you are sending a post request to a redirect route which shouldn't really work. http://programmers.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect

Maybe you should rewrite your POST to submit directly to the https endpoint?

**Comment by nickdbush** [comment]
I just thought it was strange as it worked with all my other routes. I'll heed your advice though and refactor my code. Thanks!



From: Damian Kaczmarek

Sent: Sunday, 10 April, 23:23

Subject: Re: [virtkick/http-master] POST transformed to GET request (#121)

To: virtkick/http-master

Cc: Nicholas Bush



Hmm, it seems you are sending a post request to a redirect route which shouldn't really work. http://programmers.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect


Maybe you should rewrite your POST to submit directly to the https endpoint?
