### ISSUE TITLE
windows installation 

### ISSUE THREAD

**Issue by osadan** [virtkick/http-master#123]
That's not an issue but an information regarding the installation in Windows 10
when I tried to install the plugin in Windows machine :-( 
Node js version 7.3.0 
npm version 3.10.10
I ran with a few problems 
that was resolved with
1. installing   npm install --global --production windows-build-tools (inside power shell as super user)
this tool also installs python and windows-build-tools 
2.installing Open Ssl from here http://slproweb.com/products/Win32OpenSSL.html  version - (Win64 OpenSSL v1.0.2j).
I also tried to install python and windows-build-tools  independently but with no success .(installing the http-master ) 
another thing I tried that might helped was 
"npm config set msvs_version 2012 --global"

the errors I received during the installation (after installing python) was 

C:\Users\------\WebstormProjects\NodeProxy\node_modules\utf-8-validate\build\validation.vcxproj(20,3): error MSB4019: The
 imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is
correct, and that the file exists on disk.

LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\-----\WebstormProjects\
NodeProxy\node_modules\ursa\build\ursaNative.vcxproj]

MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0"

**Comment by osadan** [comment]
a lot of information can be found https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

**Comment by Rush** [comment]
`utf-8-validate` is an optional dependency. If can speed up websockets but it's not mandatory by any means.

**Comment by osadan** [comment]
@Rush still you want a clean installation
