### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by gmarchi** [virtkick/http-master#130]
It seems passed a lot of time since latest update, so is this project still maintained? Moreover, during the installation npm seems warning about the use of some deprecated node modules.

**Comment by gmarchi** [comment]
Any news?

**Comment by SoftSolution12** [comment]
We maybe help for impruve the pagemens
http://softsolution.al/en/
Soft & Solution develops applications of all sizes and categories. Our methodology begins with collectin the first requirements from nontechnical representatives of businesses, institutions or organizations up to the professional development and implementation of the accurate solution.

Work your way

**Comment by kallisti5** [comment]
I'm not with virtkick, but have had the (sad) pleasure of watching this little implosion externally :-)

* virtkick open source work (the early work done was *awesome* and web ui great)
* Techstars funding
* Source code closed + virtkick made itself into a company
  * I complained and got a refund from them of my donations. Good on them for that.
* Some internal investment to make it a marketable product (unknown, happened behind closed doors)
* Looking to be purchased (like every good tech company!!!1!!!)
* Purchase fell through. https://www.virtkick.com/blog/
  * "Ultimately, the acquisition was not consummated, and Virtkick remained an independent entity."
* ????
* Profit.

I see expired certificates everywhere, and a deleted comment from them. I have a feeling the original devs lost all interest, or are busy paying back techstars or something.

**Comment by Rush** [comment]
Hello @gmarchi and @kallisti5,
First of all, http-master is an independent software project from Virtkick. It has an open source license and anybody can use it or improve it.  As for Virtkick, and we are pretty busy working on some independent contracts. 

Sorry for not replying to the issue in a promptly manner, I get a lot of notifications and some get lost in the chaos.

As the original creator of http-master, I am not actively developing it but I can tell you that it's fairly usable in it's current form. In fact we have it deployed in production with no significant issues.

If anybody is willing to pick up the project, submit PRs etc. I am happy to give them a review and merge them.

Moreover, I do not exclude myself getting back to this project should a need arise. I believe http-master is a great Node.JS based programmatic reverse-proxy solution.

Cheers
